### PR TITLE
MainActivity implementation

### PR DESCRIPTION
**Pull request by chermidap**

### CODE REVIEW

**Comment by mdelapenya** [comment]
Hey @chermidap, could you separate this pull into smaller commits?

Remember, one commit per step

**Comment by mdelapenya** [comment]
For instance:
1. Define basic main activity
2. Adding slider to activity
3. Android studio files
4. Adding font + usage
5. Include library xyz-1.0, as we need it to blah
6. Include library jkm-1.0, as we need it to blah
7. Adding main button to activity
   ...

This way it will be easier to review, and detect potential failures/bugs

Thanks!

**Comment by chermidap** [comment]
I will try to do this way for next commits

**Comment by mdelapenya** [comment]
:+1: during review process we need smaller commits, once it's merged we could squash all into one, but for review process is important to know why things are done, instead of what is done.

Closing this pull

**Comment by mdelapenya** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Pull request closed without merging**
